# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GUPEYA0KPIuQ1ZKwoc9fvTe_ZxFt0ca6

# Configuration

- Update `config.py` file with your API keys and other configuration settings.

# File Structure

- `main.py`: Main Python script for interacting with WhatsApp and Gmail APIs.
- `config.py`: Configuration file for storing API keys and other settings.
- `whatsapp.csv`: Sample CSV file containing WhatsApp conversations.
- `gmail.csv`: Sample CSV file containing Gmail emails.
- `README.md`: Project documentation.

# Contributors

- [Kanika Varandani](https://www.linkedin.com/in/ka-nick-ka/)
"""